### ISSUE TITLE
Incorporate tietokilta/dev to FK production

### ISSUE THREAD

**Issue by nikosavola** [fyysikkokilta/ilmomasiina#9]
[tietokilta/dev](https://github.com/Tietokilta/ilmomasiina/tree/dev) seems to be where future development is going to happen so better refactor FK changes to support this.

#### Potential challenges
* Check that TypeScript works -> convert current FK code to TS
* Use Docker Compose for backend instead of older method

**Comment by leevironty** [comment]
Merged to azure/dev. Guild look, translations and images were sacrificed in the process -> needs to be reimplemented.
